In [19]:
import fiona
import rasterio

import numpy as np
import pandas as pd

In [12]:
naip_2013_fns = []
naip_2017_fns = []
with fiona.open("../data/dfc2021_index.geojson") as f:
    for row in f:
        properties = row["properties"]
        naip_2013_fns.append(properties["naip-2013"])      
        naip_2017_fns.append(properties["naip-2017"])

In [57]:
sampled_pixels = []

for i, fn in enumerate(naip_2013_fns):
    if i % 100 == 0:
        print(i, len(naip_2013_fns))
    with rasterio.open(fn) as f:
        data = f.read().reshape(4,-1)
        
    mask = np.sum(data==0, axis=0) == 4
    data = data[:,~mask]
    num_samples = min(int(1e5), data.shape[1])
    idxs = np.random.choice(data.shape[1], size=num_samples)
    
    pixels = data[:,idxs]
    sampled_pixels.append(pixels)

0 2250
100 2250
200 2250
300 2250
400 2250
500 2250
600 2250
700 2250
800 2250
900 2250
1000 2250
1100 2250
1200 2250
1300 2250
1400 2250
1500 2250
1600 2250
1700 2250
1800 2250
1900 2250
2000 2250
2100 2250
2200 2250


In [61]:
sampled_pixels = np.concatenate(sampled_pixels, axis=1)

In [63]:
sampled_pixels.mean(axis=1, dtype=np.float64)

array([117.00209561, 130.7450301 , 122.49708863, 159.29880331])

In [64]:
sampled_pixels.std(axis=1, dtype=np.float64)

array([38.16284038, 36.67787379, 24.29653016, 66.22487842])

In [65]:
sampled_pixels = []

for i, fn in enumerate(naip_2017_fns):
    if i % 100 == 0:
        print(i, len(naip_2017_fns))
    with rasterio.open(fn) as f:
        data = f.read().reshape(4,-1)
        
    mask = np.sum(data==0, axis=0) == 4
    data = data[:,~mask]
    num_samples = min(int(1e5), data.shape[1])
    idxs = np.random.choice(data.shape[1], size=num_samples)
    
    pixels = data[:,idxs]
    sampled_pixels.append(pixels)

0 2250
100 2250
200 2250
300 2250
400 2250
500 2250
600 2250
700 2250
800 2250
900 2250
1000 2250
1100 2250
1200 2250
1300 2250
1400 2250
1500 2250
1600 2250
1700 2250
1800 2250
1900 2250
2000 2250
2100 2250
2200 2250


In [66]:
sampled_pixels = np.concatenate(sampled_pixels, axis=1)

In [67]:
sampled_pixels.mean(axis=1, dtype=np.float64)

array([ 72.84036072,  86.83287392,  76.78157846, 130.82056531])

In [68]:
sampled_pixels.std(axis=1, dtype=np.float64)

array([41.77634937, 34.65967416, 28.75779489, 58.94652752])